from django.urls import path

from accounts import views

urlpatterns = [
    path('register/', views.signup, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password-reset/', views.PasswordResetRequestView.as_view(), name='password_reset'),
    path('password-reset/sent/', views.PasswordResetSentView.as_view(), name='password_reset_done'),
    path(
        'password-reset/confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmPageView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'password-reset/complete/',
        views.PasswordResetCompletePageView.as_view(),
        name='password_reset_complete',
    ),
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    path('verify-email/', views.verify_email_pending, name='verify_email_pending'),
    path('verify-email/resend/', views.resend_verification_email, name='resend_verification_email'),
    path('notifications/', views.notifications_list, name='notifications_list'),
    path('notifications/read-all/', views.notifications_mark_all_read, name='notifications_mark_all_read'),
    path('notifications/<int:notification_id>/read/', views.notification_mark_read, name='notification_mark_read'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('onboarding/role/', views.onboarding_role, name='onboarding_role'),
    path('onboarding/mentee/', views.onboarding_mentee, name='onboarding_mentee'),
    path('onboarding/mentor/', views.onboarding_mentor, name='onboarding_mentor'),
    path('mentors/', views.mentor_list, name='mentor_list'),
    path('mentors/<slug:slug>/', views.mentor_detail, name='mentor_detail'),
    path('mentors/<slug:slug>/book/', views.book_session, name='book_session'),
    path('mentors/<slug:slug>/slots/', views.api_slots, name='api_slots'),
    path('bookings/<int:booking_id>/attendance/', views.booking_attendance, name='booking_attendance'),
    path('bookings/<int:booking_id>/rate/', views.booking_rate, name='booking_rate'),
    path('bookings/<int:booking_id>/manage/', views.mentor_booking_manage, name='mentor_booking_manage'),
    path('bookings/<int:booking_id>/confirm/', views.booking_confirm, name='booking_confirm'),
    path('mentee/photo/', views.mentee_photo_upload, name='mentee_photo_upload'),
    path('mentee/cabinet/', views.mentee_cabinet, name='mentee_cabinet'),
    path('mentee/profile/', views.mentee_profile, name='mentee_profile'),
    path('mentee/chats/', views.mentee_chats, name='mentee_chats'),
    path('mentor/schedule/', views.mentor_schedule, name='mentor_schedule'),
    path('mentor/schedule/slots/', views.mentor_schedule_api, name='mentor_schedule_api'),
    path('mentor/schedule/<int:slot_id>/edit/', views.edit_slot, name='edit_slot'),
    path('mentor/schedule/<int:slot_id>/delete/', views.delete_slot, name='delete_slot'),
    path(
        'chats/<int:conversation_id>/messages/<int:message_id>/delete/',
        views.chat_message_delete,
        name='chat_message_delete',
    ),
    path('chats/<int:conversation_id>/messages/', views.chat_messages_api, name='chat_messages_api'),
    path('chats/<int:conversation_id>/shared/', views.chat_shared_api, name='chat_shared_api'),
    path(
        'chats/<int:conversation_id>/attachments/<int:attachment_id>/',
        views.chat_attachment_download,
        name='chat_attachment_download',
    ),
    path('mentor/chats/<int:conversation_id>/', views.mentor_chat_detail, name='mentor_chat_detail'),
    path('mentee/chats/<int:conversation_id>/', views.mentee_chat_detail, name='mentee_chat_detail'),
    path('mentor/cabinet/', views.mentor_cabinet, name='mentor_cabinet'),
    path('mentor/anketa/', views.mentor_anketa, name='mentor_anketa'),
    path('mentor/chats/', views.mentor_chats, name='mentor_chats'),
    path('mentees/<int:user_id>/', views.mentee_detail, name='mentee_detail'),
    path('mentor/photo/', views.mentor_photo_upload, name='mentor_photo_upload'),
]
