# Generated by Django 5.2.15 on 2026-06-06 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Направление')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Лет опыта')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Компания')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Портфолио (URL)')),
                ('portfolio_text', models.TextField(blank=True, verbose_name='Портфолио (описание)')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='Статус модерации')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждён администратором')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('sessions_count', models.PositiveIntegerField(default=0, verbose_name='Проведено сессий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
                ('specializations', models.ManyToManyField(blank=True, related_name='mentors', to='accounts.specialization')),
            ],
            options={
                'verbose_name': 'Профиль ментора',
                'verbose_name_plural': 'Профили менторов',
            },
        ),
        migrations.CreateModel(
            name='MentorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='Организация')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Слот доступности',
                'verbose_name_plural': 'Слоты доступности',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MentorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='confirmed', max_length=12)),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.mentorprofile')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='accounts.availabilityslot')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('goals', models.TextField(blank=True, verbose_name='Цели обучения')),
                ('level', models.CharField(blank=True, choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=10, verbose_name='Уровень')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='interested_mentees', to='accounts.specialization')),
            ],
            options={
                'verbose_name': 'Профиль менти',
                'verbose_name_plural': 'Профили менти',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('mentee', 'Менти (ученик)'), ('mentor', 'Ментор'), ('both', 'Обе роли')], max_length=10, verbose_name='Роль на платформе')),
                ('active_role', models.CharField(choices=[('mentee', 'Менти'), ('mentor', 'Ментор')], default='mentee', max_length=10, verbose_name='Активная роль')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Онбординг завершён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('mentor', 'date', 'start_time'), name='unique_mentor_slot'),
        ),
    ]
