# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mentorskill_mentorconsultationtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('period', models.CharField(blank=True, max_length=120, verbose_name='Период')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Место работы',
                'verbose_name_plural': 'Места работы',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
