# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mentorworkexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorworkexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AddField(
            model_name='mentorworkexperience',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='По настоящее время'),
        ),
        migrations.AddField(
            model_name='mentorworkexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
