# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mentorworkexperience_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специальность')),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
