# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mentorprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('portfolio', 'Портфолио'), ('social', 'Социальная сеть')], max_length=10, verbose_name='Тип')),
                ('platform', models.CharField(blank=True, max_length=20, verbose_name='Платформа')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Ссылка профиля',
                'verbose_name_plural': 'Ссылки профиля',
                'ordering': ['link_type', 'sort_order', 'id'],
            },
        ),
    ]
