# Generated by Django 5.2.15 on 2026-06-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_recommendation_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menteeprofile',
            options={'verbose_name': 'Анкета менти', 'verbose_name_plural': 'Анкеты менти'},
        ),
        migrations.AlterModelOptions(
            name='mentorprofile',
            options={'verbose_name': 'Анкета ментора', 'verbose_name_plural': 'Менторы'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователей'},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_user_id_b29cd4_idx',
            old_name='accounts_no_user_id_6f0a8a_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationevent',
            new_name='accounts_re_event_t_da91e5_idx',
            old_name='accounts_re_event_t_1c2d3e_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationevent',
            new_name='accounts_re_exposur_a907e7_idx',
            old_name='accounts_re_exposur_4f5a6b_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationexposure',
            new_name='accounts_re_mentee__dc8dde_idx',
            old_name='accounts_re_mentee__8f2d0a_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationexposure',
            new_name='accounts_re_mentor__70c256_idx',
            old_name='accounts_re_mentor__d0f8f1_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationexposure',
            new_name='accounts_re_created_47bc40_idx',
            old_name='accounts_re_created_0a1b2c_idx',
        ),
    ]
